name: Pack GlobalSign Agent
on: [push]

jobs:
  macos:
    name: MacOS
    strategy:
      matrix:
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Install ninja
        run: brew install ninja
      - name: Build
        run: npm run build:config && npm run build:rx64
      # - name: Run tests
      #   run: npm test
      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package for ${{ matrix.os }}
          path: out/Release_x64/libpvpkcs11.dylib
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
    name: Windows ${{ matrix.platform }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Install ninja
        shell: powershell
        run: |
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $ninjaLink = "https://github.com/ninja-build/ninja/releases/download/v1.11.0/ninja-win.zip"
          $ninjaZip = "ninja.zip"
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Write-Output "Downloading $ninjaLink file"
          Invoke-WebRequest -Uri "$ninjaLink" -OutFile $ninjaZip
          Write-Output "Extracting $ninjaZip file"
          [System.IO.Compression.ZipFile]::ExtractToDirectory($ninjaZip, ".")
      - name: Build Config
        run: npm run build:config
      - name: List out folder
        run: |
          dir out
          dir out/Release_${{ matrix.platform }}
      - name: Build Library
        run: npm run build:r${{ matrix.platform }}
      # - name: Run tests
      #   run: npm test
      - name: Create artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: out/Release_${{ matrix.platform }}/pvpkcs11.dll